### PR TITLE
fix: save store paths to file

### LINKED ISSUE #4: Push  Argument list too long
my yaml:
```yaml
name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3  
    - name: Setup Attic cache
      uses: ryanccn/attic-action@v0
      with:
        endpoint: ${{ secrets.ATTIC_ENDPOINT }}
        cache: ${{ secrets.ATTIC_CACHE }}
        token: ${{ secrets.ATTIC_TOKEN }}
    - run: nix flake update
    - run: nix flake check --impure

```

Post Setup Attic Cache:
Post job cleanup.
Error: An error occurred trying to start process '/nix/store/xasbpkm59l734mh5d40jibqga8d9q6n-github-runner-.307.1/lib/externals/node16/bin/node' with working directory '/run/github-runner/machineid/repo/repo'. Argument list too long

any ideas?

### PR DESCRIPTION
**Pull request by gallexme**
Squash and Merge if its okay
hope it fixes  #4

### CODE REVIEW

**Comment by ryanccn** [comment]
I don't think this would fix the issue, the same huge blob of arguments are still passed to attic

**Comment by gallexme** [comment]
> I don't think this would fix the issue, the same huge blob of arguments are still passed to attic

Your chunking of 25 paths send to attic is still in it, it works for me after a 1.5h long flake check it pushed the built paths for another 1h to my cache (passing the job count to attic push may be a good feature/sometimes 1 path gets stuck for.very long time at 20bits/s)

**Comment by gallexme** [comment]
Probably could also pipe the paths to attic push for better speeds ,with maybe a timeout setting/ retry

**Comment by ryanccn** [comment]
Format the code properly with Prettier please (`pnpm run format`)

**Comment by gallexme** [comment]
@ryanccn  done!

**Review by ryanccn — APPROVED** [review]

**Pull request merged**
